name: "Setup Python Dependencies"
description: "Install Python dependencies with constraints for versiontracker"
inputs:
  requirements:
    description: "Install base requirements.txt"
    required: false
    default: "true"
  dev-requirements:
    description: "Install requirements-dev.txt"
    required: false
    default: "true"
  install-package:
    description: "Install package in editable mode"
    required: false
    default: "true"

runs:
  using: "composite"
  steps:
    - name: Upgrade pip
      shell: bash
      run: python -m pip install --upgrade pip

    - name: Install base requirements
      if: inputs.requirements == 'true'
      shell: bash
      run: pip install -c constraints.txt -r requirements.txt

    - name: Install dev requirements
      if: inputs.dev-requirements == 'true'
      shell: bash
      run: pip install -c constraints.txt -r requirements-dev.txt

    - name: Install package
      if: inputs.install-package == 'true'
      shell: bash
      run: pip install -e .
