"""Application management module for VersionTracker."""

# Backward-compatibility imports from parent modules
from ..cache import read_cache, write_cache
from ..utils import run_command
from ..version import partial_ratio

# Cache components
from .cache import (
    AdaptiveRateLimiter,
    RateLimiter,
    RateLimiterProtocol,
    SimpleRateLimiter,
    _AdaptiveRateLimiter,
    _brew_casks_cache,
    _brew_search_cache,
    clear_homebrew_casks_cache,
    get_homebrew_casks_cached,
)

# Finder components
from .finder import (
    BREW_CMD,
    BREW_PATH,
    BREW_SEARCH,
    HAS_PROGRESS,
    MAX_ERRORS,
    _brew_search_cache,  # noqa: F811 - finder's cache shadows cache.py's
    _check_cache_for_cask,
    _check_cask_installable_with_cache,
    _create_batches,
    _create_future_submissions,
    _create_rate_limiter,
    _execute_brew_search,
    _execute_cask_installable_check,
    _get_error_message,
    _get_existing_brews,
    _handle_batch_error,
    _handle_brew_search_result,
    _handle_cask_installable_error,
    _handle_future_exception,
    _handle_future_result,
    _is_async_homebrew_available,
    _populate_cask_versions,
    _process_batch_result,
    _process_brew_batch,
    _process_brew_search_batches,
    _process_completed_futures,
    _process_with_progress_bar,
    _process_without_progress_bar,
    _should_show_progress,
    _update_cache_with_installable,
    _validate_batch_preconditions,
    check_brew_install_candidates,
    check_brew_update_candidates,
    get_applications,
    get_applications_from_system_profiler,
    get_cask_version,
    get_homebrew_casks,
    get_homebrew_casks_list,
    is_app_in_app_store,
    is_brew_cask_installable,
    is_homebrew_available,
    smart_progress,
)

# Matcher components
from .matcher import (
    _batch_process_brew_search,
    _find_matching_cask,
    _normalize_and_validate_search_term,
    _process_brew_search,
    _process_single_app_search,
    _wait_for_rate_limit,
    filter_brew_candidates,
    filter_out_brews,
    get_homebrew_cask_name,
    search_brew_cask,
)

__all__ = [
    # Backward-compatibility
    "read_cache",
    "write_cache",
    "run_command",
    "partial_ratio",
    # Cache components
    "AdaptiveRateLimiter",
    "RateLimiter",
    "RateLimiterProtocol",
    "SimpleRateLimiter",
    "_AdaptiveRateLimiter",
    "_brew_casks_cache",
    "_brew_search_cache",
    "clear_homebrew_casks_cache",
    "get_homebrew_casks_cached",
    # Finder constants
    "BREW_CMD",
    "BREW_PATH",
    "BREW_SEARCH",
    "HAS_PROGRESS",
    "MAX_ERRORS",
    # Finder functions
    "_check_cache_for_cask",
    "_check_cask_installable_with_cache",
    "_create_batches",
    "_create_future_submissions",
    "_create_rate_limiter",
    "_execute_brew_search",
    "_execute_cask_installable_check",
    "_get_error_message",
    "_get_existing_brews",
    "_handle_batch_error",
    "_handle_brew_search_result",
    "_handle_cask_installable_error",
    "_handle_future_exception",
    "_handle_future_result",
    "_is_async_homebrew_available",
    "_populate_cask_versions",
    "_process_batch_result",
    "_process_brew_batch",
    "_process_brew_search_batches",
    "_process_completed_futures",
    "_process_with_progress_bar",
    "_process_without_progress_bar",
    "_should_show_progress",
    "_update_cache_with_installable",
    "_validate_batch_preconditions",
    "check_brew_install_candidates",
    "check_brew_update_candidates",
    "get_applications",
    "get_applications_from_system_profiler",
    "get_cask_version",
    "get_homebrew_casks",
    "get_homebrew_casks_list",
    "is_app_in_app_store",
    "is_brew_cask_installable",
    "is_homebrew_available",
    "smart_progress",
    # Matcher functions
    "_batch_process_brew_search",
    "_find_matching_cask",
    "_normalize_and_validate_search_term",
    "_process_brew_search",
    "_process_single_app_search",
    "_wait_for_rate_limit",
    "filter_brew_candidates",
    "filter_out_brews",
    "get_homebrew_cask_name",
    "search_brew_cask",
]
