name: Security Audit

on:
  schedule:
    # Run security audit daily at 6 AM UTC
    - cron: '0 6 * * *'
  push:
    paths:
      - 'requirements*.txt'
      - 'pyproject.toml'
      - '.github/workflows/security-audit.yml'
  pull_request:
    paths:
      - 'requirements*.txt'
      - 'pyproject.toml'
  workflow_dispatch:

env:
  PYTHONUNBUFFERED: 1
  FORCE_COLOR: 1

jobs:
  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install safety pip-audit bandit[toml]
          pip install -r requirements.txt
          pip install -r requirements-dev.txt

      - name: Run safety check
        run: |
          echo "## Safety Check Results" >> security-report.md
          echo '```' >> security-report.md
          safety check --json > safety-results.json || true
          if [ -s safety-results.json ]; then
            safety check --short-report >> security-report.md || true
          else
            echo "No known security vulnerabilities found." >> security-report.md
          fi
          echo '```' >> security-report.md
          echo "" >> security-report.md

      - name: Run pip-audit
        run: |
          echo "## Pip-Audit Results" >> security-report.md
          echo '```' >> security-report.md
          pip-audit --format=text >> security-report.md || true
          echo '```' >> security-report.md
          echo "" >> security-report.md

      - name: Run Bandit security scan
        run: |
          echo "## Bandit Security Scan" >> security-report.md
          echo '```' >> security-report.md
          bandit -r versiontracker/ -f txt >> security-report.md || true
          echo '```' >> security-report.md
          echo "" >> security-report.md

      - name: Create security summary
        run: |
          echo "# Security Audit Report" > security-summary.md
          echo "**Generated**: $(date -u)" >> security-summary.md
          echo "**Repository**: ${{ github.repository }}" >> security-summary.md
          echo "**Commit**: ${{ github.sha }}" >> security-summary.md
          echo "" >> security-summary.md
          cat security-report.md >> security-summary.md

      - name: Upload security report
        uses: actions/upload-artifact@v4
        with:
          name: security-audit-report
          path: |
            security-summary.md
            safety-results.json
          retention-days: 30

      - name: Comment on PR (if applicable)
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            if (fs.existsSync('security-summary.md')) {
              const report = fs.readFileSync('security-summary.md', 'utf8');
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: `## 🔒 Security Audit Report\n\n${report}`
              });
            }

      - name: Fail on critical vulnerabilities
        run: |
          if grep -q "CRITICAL\|HIGH" security-report.md; then
            echo "❌ Critical or high severity vulnerabilities found!"
            echo "Please review the security report and update dependencies."
            exit 1
          else
            echo "✅ No critical vulnerabilities found."
          fi
